setwd('C:/Users/ddhhrruuvv27/Desktop/Doc')
require(tm)
fo=file('doc',open="r")
doc=readLines(fo)
#fo=file('title',open="r")
#titles=readLines(fo)
corp <- Corpus(VectorSource(doc))
docs <- tm_map(corp, removePunctuation)
docs <- tm_map(docs,content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, stripWhitespace)
#docs <- tm_map(docs,stemDocument)
docs <- tm_map(docs, stemDocument, language = "english")
dtm <-DocumentTermMatrix(docs,control = list(weighting = function(x) weightTfIdf(x, normalize = TRUE)))
dtm = removeSparseTerms(dtm,0.7)
out <- capture.output(inspect(dtm))
options(max.print = 2147483647)
cat("Classification results", out, file="result.txt", sep="\n", append=TRUE)
freqterms100 <- findFreqTerms(dtm,2)

out <- capture.output(freqterms100)
options(max.print = 2147483647)
cat("Frequent terms in atleast 2 documents", out, file="result.txt", sep="\n", append=TRUE)
freqterms100 <- findFreqTerms(dtm,3)
out <- capture.output(freqterms100)
options(max.print = 2147483647)
cat("Frequent terms in atleast 3 documents", out, file="result.txt", sep="\n", append=TRUE)

freqterms100 <- findFreqTerms(dtm,4)
out <- capture.output(freqterms100)
options(max.print = 2147483647)
cat("Frequent terms in atleast 4 documents", out, file="result.txt", sep="\n", append=TRUE)
freqterms100 <- findFreqTerms(dtm,5)
out <- capture.output(freqterms100)
options(max.print = 2147483647)
cat("Frequent terms in atleast 5 documents", out, file="result.txt", sep="\n", append=TRUE)
dtm <- as.data.frame(inspect(dtm))
rownames(dtm) <- 1:nrow(dtm)
vector <- c(1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,1,1,2,2,3,3,4,4,5,5,6,6)
container <- create_container(dtm,t(vector),trainSize=1:55, testSize=56:67,virgin= FALSE)
models <- train_models(container, algorithms=c("MAXENT","SVM","GLMNET","SLDA","TREE","BAGGING","BOOSTING","RF"))
results <- classify_models(container, models)
out <- capture.output(results)
options(max.print = 2147483647)
cat("#####FINAL RESULYS AFTER CLASSIFICATION#######", out, file="result.txt", sep="\n", append=TRUE)
analytics <- create_analytics(container, results)
out <- capture.output(analytics)
options(max.print = 2147483647)
cat("##################ANALYTICS################", out, file="result.txt", sep="\n", append=TRUE)
out <- capture.output(summary(analytics))
options(max.print = 2147483647)
cat("#######################################################################################", out, file="result.txt", sep="\n", append=TRUE)
